[request_definition]
r = user, domain, resource, action

[policy_definition]
p = user, domain, eft, resource, action

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny)) # deny overrides any allow

[matchers]
m = g(r.user, p.user, r.domain) && r.domain == p.domain && r.resource == p.resource && r.action == p.action